修改自定义附属矿物科技OreTech信息
SlimefunGuguProject/Slimefun-Wiki pull request #107
Opened 2024-02-24 06:29 UTC by HiTech0926

修改自定义附属矿物科技OreTech信息

2024-02-24 17:08 UTC, ybw0014 requested changes

2024-02-24 17:08 UTC, ybw0014 commented on pages/Addons.md
> +OreTech 矿物科技 | Chenmose HiTech0926 | <details><summary>展开</summary>添加了一系列机器到粘液书中 </details> | [更多信息](https://github.com/HiTech0926/OreTech#readme) | [官方版](https://github.com/HiTech0926/OreTech) | [官方
```suggestion
OreTech 矿物科技 | Chenmose, HiTech0926 | <details><summary>展开</summary>添加了一系列机器到粘液书中 </details> | [更多信息](https://github.com/HiTech0926/OreTech#readme) | [官方版](https://github.com/HiTech0926/OreTech) | [官方版](https://github.com/HiTech0926/OreTech)
```
仓库不存在

2024-02-25 15:59 UTC, HiTech0926 commented on pages/Addons.md
> +OreTech 矿物科技 | Chenmose HiTech0926 | <details><summary>展开</summary>添加了一系列机器到粘液书中 </details> | [更多信息](https://github.com/HiTech0926/OreTech#readme) | [官方版](https://github.com/HiTech0926/OreTech) | [官方
呃呃抱歉忘记改仓库名了，已经修改
[](https://github.com/HiTech0926/OreTech)

2024-02-25 16:00 UTC, HiTech0926 commented on pages/Addons.md
> +OreTech 矿物科技 | Chenmose HiTech0926 | <details><summary>展开</summary>添加了一系列机器到粘液书中 </details> | [更多信息](https://github.com/HiTech0926/OreTech#readme) | [官方版](https://github.com/HiTech0926/OreTech) | [官方
呃呃抱歉忘记改仓库名了，已经修改
[](https://github.com/HiTech0926/OreTech)

2024-02-25 16:00 UTC, HiTech0926 commented
呃呃抱歉忘记改仓库名了，已经修改
[](https://github.com/HiTech0926/OreTech)

2024-02-25 16:17 UTC, ybw0014 commented on pages/Addons.md
> +OreTech 矿物科技 | Chenmose HiTech0926 | <details><summary>展开</summary>添加了一系列机器到粘液书中 </details> | [更多信息](https://github.com/HiTech0926/OreTech#readme) | [官方版](https://github.com/HiTech0926/OreTech) | [官方
另外，作者之间使用逗号分隔

2024-02-26 16:24 UTC, ybw0014 requested changes

2024-02-26 16:24 UTC, ybw0014 commented on pages/Addons.md
> +OreTech 矿物科技 | Chenmose,HiTech0926 | <details><summary>展开</summary>添加了一系列机器到粘液书中 </details> | [更多信息](https://github.com/HiTech0926/OreTech#readme) | [官方版](https://github.com/HiTech0926/OreTech) | [官方
```suggestion
OreTech 矿物科技 | Chenmose, HiTech0926 | <details><summary>展开</summary>添加了一系列机器到粘液书中 </details> | [更多信息](https://github.com/HiTech0926/OreTech#readme) | [官方版](https://github.com/HiTech0926/OreTech) | [官方版](https://github.com/HiTech0926/OreTech)
```

2024-05-01 05:04 UTC, merged