add&change: ryken slime customizer
SlimefunGuguProject/Slimefun-Wiki pull request #116
Opened 2024-07-02 11:14 UTC by HiTech0926

2024-07-04 15:16 UTC, ybw0014 requested changes

2024-07-04 15:16 UTC, ybw0014 commented on pages/Addons.md
> +以下均为SC自定义粘液附属的配置。
英文前后加空格。

2024-07-04 15:16 UTC, ybw0014 commented on pages/Addons.md
> +### :anchor: RSC自定义粘液附属 :id=ryken-slime-customizer-addons
英文前后加空格

2024-07-04 19:02 UTC, HiTech0926 commented on pages/Addons.md
> +### :anchor: RSC自定义粘液附属 :id=ryken-slime-customizer-addons
> 英文前后加空格

已修改

2024-07-04 20:00 UTC, ybw0014 requested changes

2024-07-04 20:00 UTC, ybw0014 commented on pages/Addons.md
> +
多了一行

2024-07-05 10:36 UTC, HiTech0926 commented on pages/Addons.md
> +
> 多了一行

改了

2024-07-05 11:52 UTC, ybw0014 approved these changes

2024-07-05 11:53 UTC, merged