更新新表格（暂时不合并）
SlimefunGuguProject/Slimefun-Wiki pull request #57
Opened 2022-03-24 03:51 UTC by haiman233

2022-03-24 05:00 UTC, ybw0014 commented on pages/Addons.md
> +SlimefunRecipeManager (RC-27) 粘液配方修改器 | qwertyuioplkjhgfd | <details><summary>展开</summary>你可以通过该插件修改粘液科技原版配方</details> | N/A | [官方版](https://github.com/qwertyuioplkjhgfd/SlimefunRecipeManager) | [官方版
这插件没有用，感觉没必要写在这

2022-04-02 16:50 UTC, ybw0014 requested changes

2022-04-02 16:50 UTC, ybw0014 commented on pages/Addons.md
> +GuizhanCraft (RC-30) 鬼斩科技 | ybw0014 | <details><summary>展开</summary>（国产）该附属由鬼斩(ybw0014)一手开发，旨在向游戏中加入新机器、新玩法</details> | N/A | [官方版](https://github.com/FlickerProjects/SlimefunItemExpansion) | [官方版](h
.

2022-04-02 16:50 UTC, ybw0014 commented on pages/Addons.md
> +Bump (RC-30) Bump魔法 | bxx2004 | <details><summary>展开</summary>（国产）该附属添加了武器、护甲鉴定系统，以及一些食物与饮料、魔法武器</details> | N/A | [官方旧版](https://www.mcbbs.net/thread-1125935-1-1.html) / [代理方新版](https://github.com/h
链接是指向英文版的

2022-04-02 23:06 UTC, haiman233 commented
ok

2022-04-02 23:09 UTC, ybw0014 commented on pages/Addons.md
> +GuizhanCraft (RC-30) 鬼斩科技 | ybw0014 | <details><summary>展开</summary>（国产）该附属由鬼斩(ybw0014)一手开发，旨在向游戏中加入新机器、新玩法</details> | N/A | [官方版](https://github.com/FlickerProjects/SlimefunItemExpansion) | [官方版](h
还有这个

2022-04-03 01:00 UTC, ybw0014 requested changes

2022-04-03 01:00 UTC, ybw0014 commented on pages/Addons.md
> +GuizhanCraft (RC-30) 鬼斩科技 | ybw0014 | <details><summary>展开</summary>（国产）该附属由鬼斩(ybw0014)一手开发，旨在向游戏中加入新机器、新玩法</details> | N/A | [官方版](https://github.com/FlickerProjects/SlimefunItemExpansion) | [官方版](h
地址错误

2022-04-03 01:03 UTC, ybw0014 approved these changes

2022-04-03 01:04 UTC, merged

2022-04-03 01:04 UTC, haiman233 commented
等会

2022-04-03 01:04 UTC, haiman233 commented
我看看哈

2022-04-03 01:05 UTC, haiman233 commented
没事了